typography_spectrum: 0.54603
color:
  brandColors:
    - '#100e0f'
    - '#bfb6ad'
    - '#9f8869'
    - '#3f687c'
    - '#fffdfe'
  brandStrength: 0.686043395427987
  lightness: 0.2651996451895684
  saturation: 0.7042466208804399
  rhythmicContrast: 0.5001765403430909
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5524
analytics:
  google: null
  facebook: null
  twitter: null
name: 81AlfaSpider
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Condition of The Car
    id: 284cf28e-9813-4e58-b5b1-069aceb00693
    type: content
  - name: The History Of The Car
    id: 23735bdf-29ba-4954-bef7-f18946b648a4
    type: content
  - name: 'Alfa Ramblings '
    id: 755f8cf5-01d0-470d-b2a2-4ad27f5d0e58
    type: content
  - name: Thank you
    id: 123c081a-f26f-4350-b0d3-16532ae7a9ad
    type: content
favicon: null
title: 81 Alfa Romeo Spider Veloce
description: Fun For Sale
purpose: []
