name: 81AlfaSpider
favicon: null
layout_spectrum: 0.06457483791746199
typography_spectrum: 0.1866214917972684
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.686043395427987
  lightness: 0.2651996451895684
  saturation: 0.7042466208804399
  rhythmicContrast: 0.5001765403430909
purpose: []
