name: 81AlfaSpider
favicon: null
layout_spectrum: 0.49637
typography_spectrum: 0.54603
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a0b1cb'
    - '#ffffff'
    - '#090909'
    - '#516c87'
    - '#a64e3a'
  brandStrength: 0.686043395427987
  lightness: 0.2651996451895684
  saturation: 0.7042466208804399
  rhythmicContrast: 0.5001765403430909
purpose: []
